name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build UI
        run: |
          cd ui
          pnpm install
          pnpm run publish
          cd ..

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Generate version
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="v0.0.0-${SHORT_SHA}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          mkdir -p dist

          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o dist/toyreduce-linux-amd64 ./cmd/toyreduce

          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o dist/toyreduce-linux-arm64 ./cmd/toyreduce

          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o dist/toyreduce-darwin-amd64 ./cmd/toyreduce

          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o dist/toyreduce-darwin-arm64 ./cmd/toyreduce

          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -o dist/toyreduce-windows-amd64.exe ./cmd/toyreduce

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.version.outputs.version }} \
            --title "Release ${{ steps.version.outputs.version }}" \
            --notes "Automated release from commit ${{ steps.version.outputs.short_sha }}" \
            dist/*
